kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rocketmq-data-a
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rocketmq-data-b
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client