apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-a
  namespace: rocketmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-a
  template:
    metadata:
     labels:
       app: rocketmq-a
    spec:
      containers:
      - name: broker
        image: 192.168.195.2/dev/rocketmq:v4.4.0
        command: ["sh","-c","/opt/rocketmq-4.4.0/bin/mqbroker  -c /opt/rocketmq-4.4.0/conf/broker-a.properties"]
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /root/logs
            name: rocketmq-data
            subPath: mq-brokeroptlogs
          - mountPath: /root/store
            name: rocketmq-data
            subPath: mq-brokeroptstore
          - name: rocketmq-broker-config
            mountPath: /opt/rocketmq-4.4.0/conf/broker-a.properties
            subPath: broker-a.properties
        env:
          - name: MAX_POSSIBLE_HEAP
            value: "4294967296"
      - name: namesrv
        image: 192.168.195.2/dev/rocketmq:v4.4.0
        command: ["sh","mqnamesrv"]
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /root/logs
            name: rocketmq-data
            subPath: mq-namesrvoptlogs
          - mountPath: /root/store
            name: rocketmq-data
            subPath: mq-namesrvoptstore
        env:
          - name: MAX_POSSIBLE_HEAP
            value: "1073741824"
      volumes:
      - name: rocketmq-data
        persistentVolumeClaim:
          claimName: rocketmq-data-a
      - name: bocketmq-broker-config
        configMap:
          name: bocketmq-broker-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rocketmq-a
  name: rocketmq-a
  namespace: rocketmq
spec:
  ports:
  - name: rocketmq-namesrv
    port: 9876
  selector:
    app: rocketmq-a

